travis:
  secure:
    BINSTAR_TOKEN: Ki0yWy3zNSawpLN8aFEggX0NTJtt1QrjPIeC3Fy0uP2TcprFubbjHoc3GxCq+HapWKsHqouh8FwkyAKzJju7wmXWJGHTIdPbr1gWrWma4J5y3rO4hwf7KSEjVQPh2qaa/0/t1EIZmobn8CRphapMy1DWwlqiL9ctohT6taPCi/TVwdhcfk2QVsgEQAZpIwybUxv1EqPBwqwIRjwQ2R31jhQWgbrGOJ3PkjXpDLaNbSmuRdrbjfFr7UtJ/riMeQz2IBfk8oTL2RuxLoxS48B5KHHpEH8/rZOALFhsINvaG8WHaUCqLrs9odMBMd9dgtL6XERtAbXyv7z7WeRaHCrlAPM/R/q8wN3FgckFACX0WvURduBNr3BFHLtgQX1MpD0DPK+ZXlG1G2n/nugF83SMB7lzHRv1Zgxg1M1C054HrHAZgDYa+y9vxeeZ1C/iV67AXUEbTGVTYwxKTZM6PL0f/egC0PZE4qlyPG2xsQLzbDwtCIWUC+PD9itBBb56P5OyePCgAYlTPVLozD84b2YA+DOoUmTkGGbG3pLFssK8XjU4Vw+XE+8oBsfaJFDtPonjP/ZWHeyVyagHLSNrVJFBzXCBnveMeb7U/G9P56lfpUTMNAseQm10TD1NW93rzrXNX0zDtKKCq0s4xXs3AsEvWJ/MBTtucGX1k2c3zmlk1Jk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
